// import React from "react";
// import Link from "next/link";
// const Home = () => {
//   return (
//     <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
//       <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
//       <p style={{ fontSize: "18px", marginBottom: "30px" }}>
//         This project was generated By{" "}
//         <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
//           Dhiwise
//         </a>
//         . Quickly use below links to navigate through all pages.
//       </p>
//       <ul style={{ listStyle: "none", padding: "0" }}>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/browsecontent" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             BrowseContent
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/documentinformation" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             DocumentInformation
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/ratingandreview" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             RatingandReview
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/landing" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             Landing
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/usersettingsaccount" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             UserSettingsAccount
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/usercontentmanagementlibrary" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             UserContentManagementLibrary
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/vendorregistration" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             VendorRegistration
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/vendorprofilemanagementaccount" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             VendorProfileManagementAccount
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/vendorprofilemanagementcontent" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             VendorProfileManagementContent
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/vendorprofilemanagementadd" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             VendorProfileManagementAdd
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/vendorprofilemanagementlisting" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             VendorProfileManagementListing
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/vendorprofilemanagementadmin" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             VendorProfileManagementAdmin
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/vendorprofilemanagementvendor" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             VendorProfileManagementVendor
//           </Link>
//         </li>
//       </ul>
//     </div>
//   );
// };
// export default Home;

// // =======================================TEST
// import { redirect } from 'next/navigation';

// export default function Home() {
//   redirect('/landing');
// }

import Footer from "../components/Footer";
import Header from "../components/Header";
import Link from "next/link";
import BrowsecontentGroup126 from "../components/Highlight/Highlight";
import BrowseProducts from "./LandingWorkpapers";
import { Heading } from "@/components/ui";
import React from "react";

export default function BrowseContentPage() {
  return (
    <div className="w-full bg-white-a700">
      <div className="relative z-[8] flex flex-col items-center">
        <Header className="w-full px-6 md:px-10" />
      </div>
      <div className="overflow-x-scroll">
        <BrowsecontentGroup126 />
      </div>
      <div>
        <div className="mx-[60px] mt-[68px] flex items-start justify-between gap-5 md:mx-0 md:flex-col">
          <div className="w-[14%] md:w-full md:px-4 flex flex-col gap-10">

            <section>
              <Heading size="heading5xl" as="h2" className="text-[24px] font-bold">
                Collections
              </Heading>

              <ul className="mt-2 space-y-1 text-[16px] font-medium">
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Workpapers</Link></li>
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Accounting</Link></li>
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Audit</Link></li>
              </ul>
            </section>

            <section>
              <Heading size="heading5xl" as="h2" className="text-[24px] font-bold">
                Offered
              </Heading>

              <ul className="mt-2 space-y-1 text-[16px] font-medium">
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Limited-Time</Link></li>
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">On sale</Link></li>
              </ul>
            </section>

            <section>
              <Heading size="heading5xl" as="h2" className="text-[24px] font-bold">
                Product Type
              </Heading>

              <ul className="mt-2 space-y-1 text-[16px] font-medium">
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Accounting</Link></li>
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Workpaper</Link></li>
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Audit</Link></li>
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Statements</Link></li>
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Superannuation</Link></li>
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Tax</Link></li>
                <li><Link href="#" className="text-blue-600 no-underline hover:font-bold transition-all">Templates</Link></li>
              </ul>
            </section>

          </div>
          <BrowseProducts />
        </div>
        <Footer className="mb-8 ml-[52px] mr-12 mt-9 md:mx-0" />
      </div>
    </div>
  );
}