import React from "react";
import Link from "next/link";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/browsecontent" style={{ color: "#87CEFA", textDecoration: "none" }}>
            BrowseContent
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/documentinformation" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DocumentInformation
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/ratingandreview" style={{ color: "#87CEFA", textDecoration: "none" }}>
            RatingandReview
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/landing" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Landing
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/usersettingsaccount" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserSettingsAccount
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/usercontentmanagementlibrary" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserContentManagementLibrary
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/vendorregistration" style={{ color: "#87CEFA", textDecoration: "none" }}>
            VendorRegistration
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/vendorprofilemanagementaccount" style={{ color: "#87CEFA", textDecoration: "none" }}>
            VendorProfileManagementAccount
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/vendorprofilemanagementcontent" style={{ color: "#87CEFA", textDecoration: "none" }}>
            VendorProfileManagementContent
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/vendorprofilemanagementadd" style={{ color: "#87CEFA", textDecoration: "none" }}>
            VendorProfileManagementAdd
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/vendorprofilemanagementlisting" style={{ color: "#87CEFA", textDecoration: "none" }}>
            VendorProfileManagementListing
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/vendorprofilemanagementadmin" style={{ color: "#87CEFA", textDecoration: "none" }}>
            VendorProfileManagementAdmin
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/vendorprofilemanagementvendor" style={{ color: "#87CEFA", textDecoration: "none" }}>
            VendorProfileManagementVendor
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
